version: '3.8'
services:
    postgres:
        container_name: postgres
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1234
        ports:
            - '5432:5432'
        volumes:
            - postgres:/var/lib/postgresql
volumes:
    postgres:
        driver: local
