version: '3.8'
services:
    redis:
        container_name: redis
        image: redis
        command: redis-server --loglevel warning
        ports:
            - '6379:6379'
        volumes:
            - redis:/data
volumes:
    redis:
        driver: local
